In [4]:
# iniitializing variables -- using flow control -- need to initialize variables before for loops 
import numpy as np

In [23]:
N = 10
r = np.zeros(N)    # initialized before loop -- list

for i in range(N):
    r[i] = i**2

print(r)

[ 0.  1.  4.  9. 16. 25. 36. 49. 64. 81.]


In [24]:
r

array([ 0.,  1.,  4.,  9., 16., 25., 36., 49., 64., 81.])

In [25]:
del r   # deletes variable

In [26]:
r

NameError: name 'r' is not defined

In [28]:
shape = (4,5)         # create a shape variable
r = np.zeros(shape)   # zeros doesn't take a shape as does np.random.randn(x,y) to give a matrix

r

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [32]:
# append method 
N = 10000                
r = np.array([])

for i in range(N):
    r = np.append(r,i**2)

r

array([0.0000000e+00, 1.0000000e+00, 4.0000000e+00, ..., 9.9940009e+07,
       9.9960004e+07, 9.9980001e+07], shape=(10000,))

In [30]:
# letgs compare 3 methods of creating an array -- N = 10000 r[i] = i**2 
# time test! import time time.perf_counter
import time

In [49]:
N = 10000
toc = [0]*3

# list append method
tic = time.perf_counter()
r = []
for i in range(N):
    r.append(i**2)
toc[0] = (time.perf_counter() - tic)*1000

    
# numpy append method
tic = time.perf_counter()
r = np.array([])

for i in range(N):
    r = np.append(r,i**2)
toc[1] = (time.perf_counter() - tic)*1000

    
# numpy initialization method
tic = time.perf_counter()
r = np.zeros(N)    # initialized before loop -- list

for i in range(N):
    r[i] = i**2
toc[2] = (time.perf_counter() - tic)*1000

toc
# we can see that the numpy append method is the slowest - especially as the numbers grow 
# list append is usually the quickest
# good primer for deep learning

[0.7853999850340188, 22.125999996205792, 0.6711999885737896]