In [1]:
# broadcastikng in numpy

In [2]:
import numpy as np

In [14]:
X = np.array([ [1,2,3],
               [2,3,4],
               [3,4,5],
               [4,5,6] ])  # matrix


w = np.array([10,20,30])   # vector

print(X), print(' ')
print(w)

[[1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]]
 
[10 20 30]


In [15]:
Y = np.zeros(X.shape)       # to keep the original matrix

for i in range(X.shape[0]):
    Y[i,:] = X[i,:] + w

Y

array([[11., 22., 33.],
       [12., 23., 34.],
       [13., 24., 35.],
       [14., 25., 36.]])

In [18]:
# quicker way -- broadcasting - row wise

Z = X+w               # adding a matrix and a vector -- not real math due to sizes not matching
                      # not legal in linear algebra
                      # python tunrs vector in matrix to complete the task of adding togther
                      # works for addition or subtraction

print(Z), print(' ')
print(Y)

[[11 22 33]
 [12 23 34]
 [13 24 35]
 [14 25 36]]
 
[[11. 22. 33.]
 [12. 23. 34.]
 [13. 24. 35.]
 [14. 25. 36.]]


In [19]:
# broadcasting - column wise

In [20]:
v = np.array([-1,0,1,0]) # we can see we just have a row vector
v

array([-1,  0,  1,  0])

In [21]:
v = np.array([ [-1],[0],[1],[0] ]) # we can create a column vector by putting ea. value on own row
v

array([[-1],
       [ 0],
       [ 1],
       [ 0]])

In [26]:
v = np.array([-1,0,1,0], ndmin=2).T # we can specify dimensions and transpose T - we have a columnar vector!
X*v   # multiply by matrix

array([[-1, -2, -3],
       [ 0,  0,  0],
       [ 3,  4,  5],
       [ 0,  0,  0]])

In [44]:
# lets create a vector of integers 0-8 v -- reshape v into a 3x3 matrix M -- np.reshape
# repeat M into a 9x3 matrix C use np.tile
# broadcast-multiply C with V

# create vector of integers 0:8 (v)
v = np.arange(9)
print(v), print(' ')

# reshape (v) into a 3x3 matrix (M) using np.reshape
M = np.reshape(v,(3,3))    # not to be 9,3  but rather 3,1 3x down the cols and only 1x on rows
print(M), print(' ')

# repeat M into a 9x3 matrix (C) using np.tile
C = np.tile(M,(3,1))
print(C), print(' ')

# broadcast-multiple C with v
B = C*np.reshape(v,(len(v),1)) # need to reshape to fit columnar shape
print(B);

[0 1 2 3 4 5 6 7 8]
 
[[0 1 2]
 [3 4 5]
 [6 7 8]]
 
[[0 1 2]
 [3 4 5]
 [6 7 8]
 [0 1 2]
 [3 4 5]
 [6 7 8]
 [0 1 2]
 [3 4 5]
 [6 7 8]]
 
[[ 0  0  0]
 [ 3  4  5]
 [12 14 16]
 [ 0  3  6]
 [12 16 20]
 [30 35 40]
 [ 0  6 12]
 [21 28 35]
 [48 56 64]]
