In [20]:
import numpy as np # we need numpy to use functions of higher math than what pythion has by default
# need to run this line once

In [7]:
numbers = [ 1,2,3,4,5 ]

#now we can use a function for mean instead of getting the value of an output and dividing by the num of length of a list

np.mean(numbers)

np.float64(3.0)

In [11]:
# more examples -- we are not fully exploring numpy here just introducing it
np.linspace(1,7,5)

array([1. , 2.5, 4. , 5.5, 7. ])

In [12]:
# produces a numpy array with n dimesnions
x = np.linspace(1,7,5)
type(x)

numpy.ndarray

In [13]:
# we can convert lists into arrays
type(numbers)

list

In [14]:
numbers_np = np.array(numbers)

print(type(numbers))
print(type(numbers_np))

<class 'list'>
<class 'numpy.ndarray'>


In [16]:
# methods to run on np arrays
numbers_np.min()

np.int64(1)

In [17]:
numbers_np.max()

np.int64(5)

In [19]:
np.max( numbers ) # some functions/methods work on lists as well pretyends it is an np array

np.int64(5)

In [25]:
from numpy import mean as m # lets import mean we can uise this to import just one function

In [36]:
n = [ 4,2,6,9,5,1,0 ]

nn = np.array(n)

print(nn)
np.sort(nn)
print(nn)
np.mean(nn)

[4 2 6 9 5 1 0]
[4 2 6 9 5 1 0]


np.float64(3.857142857142857)